CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY,
  firstname varchar(255),
  lastname varchar(255),
  email varchar(255)
);

INSERT INTO users (id,firstname,lastname,email) VALUES (1,"McKenzie","Monroe","dui.in.sodales@nequenonquam.net"),(2,"Hakeem","Coleman","ut@nequenon.ca"),(3,"Leroy","Rodriguez","tortor.at.risus@a.net"),(4,"Darrel","Burks","nec@auctorvelit.org"),(5,"Marshall","Steele","metus@gravidaPraesent.ca"),(6,"Shay","Kinney","aliquet.vel.vulputate@adipiscing.org"),(7,"Janna","Moreno","Ut.semper@etmalesuadafames.net"),(8,"Amela","Bonner","feugiat@idsapien.net"),(9,"Dominic","Paul","erat.vitae@dictum.co.uk"),(10,"Nathan","Guerra","eu@dolor.org");
INSERT INTO users (id,firstname,lastname,email) VALUES (11,"Cathleen","Kemp","nec.tempus@est.co.uk"),(12,"Belle","Faulkner","ac@facilisis.co.uk"),(13,"Hunter","Lloyd","ac@Phasellusfermentumconvallis.org"),(14,"Warren","Taylor","tempor@Pellentesque.net"),(15,"Joel","Noble","bibendum.sed.est@arcu.ca"),(16,"Dawn","Davidson","ante@interdumNuncsollicitudin.net"),(17,"Vernon","Brennan","vel@auctorMauris.ca"),(18,"Elaine","Warner","congue.In.scelerisque@Etiambibendum.co.uk"),(19,"Mohammad","Mcgee","Mauris.molestie@felis.ca"),(20,"Troy","Tanner","rutrum.urna.nec@consectetuer.org");
INSERT INTO users (id,firstname,lastname,email) VALUES (21,"Dominic","Obrien","elit@sitamet.net"),(22,"Wang","Burt","mauris.id@ultrices.com"),(23,"Brennan","Hancock","tortor.Nunc@massa.net"),(24,"Kellie","Cohen","purus@faucibusleoin.net"),(25,"Hedda","Ferrell","malesuada.vel@etultricesposuere.co.uk"),(26,"Jerome","Mann","dictum.eu.placerat@consequatnec.ca"),(27,"Carol","Norman","semper@miAliquam.co.uk"),(28,"Marah","Waller","netus.et@etcommodoat.org"),(29,"Hilel","Hendricks","est.Nunc@bibendumsedest.com"),(30,"Odette","Shannon","Aenean@luctusCurabituregestas.ca");
INSERT INTO users (id,firstname,lastname,email) VALUES (31,"Freya","Velez","elementum@auctorquistristique.edu"),(32,"Neve","Marshall","ac@dolorQuisque.ca"),(33,"Leandra","Cox","a.feugiat.tellus@commodoat.com"),(34,"Amena","Compton","luctus.aliquet.odio@vitae.co.uk"),(35,"Kevyn","Bond","aliquet.magna.a@leo.com"),(36,"Glenna","Mcmahon","tincidunt.Donec.vitae@lobortisaugue.ca"),(37,"Jorden","Maddox","eu.augue@Aliquamrutrum.ca"),(38,"Eliana","Castaneda","mollis.Duis.sit@et.edu"),(39,"Hector","Wolf","Phasellus.vitae.mauris@ligula.ca"),(40,"Harrison","Nash","ac@ullamcorper.co.uk");
INSERT INTO users (id,firstname,lastname,email) VALUES (41,"Kieran","Reyes","scelerisque@ametorciUt.net"),(42,"Boris","Rasmussen","natoque.penatibus@nisia.org"),(43,"Holly","Dorsey","egestas.a.dui@lectusCum.org"),(44,"Guinevere","Guzman","felis.orci.adipiscing@nisi.ca"),(45,"Gwendolyn","Richard","vel.faucibus.id@ametrisusDonec.org"),(46,"Leonard","Baird","consectetuer.adipiscing@Cumsociisnatoque.net"),(47,"Ethan","Wolfe","turpis@egestasDuisac.ca"),(48,"Herrod","Underwood","Mauris.magna@ut.org"),(49,"Carol","Burns","libero.dui.nec@ametfaucibusut.com"),(50,"Brianna","Larsen","odio@dictum.ca");
INSERT INTO users (id,firstname,lastname,email) VALUES (51,"Ignacia","Russell","quis.arcu.vel@Sed.ca"),(52,"Barclay","Boyle","dictum@nisia.org"),(53,"Kristen","Terrell","egestas.nunc@justoProin.com"),(54,"Paloma","Noble","Donec.non.justo@Crasloremlorem.net"),(55,"Dolan","Graham","tellus@Maecenas.org"),(56,"Chandler","Simon","velit.justo@dictumeu.co.uk"),(57,"Iliana","Cash","mi.eleifend@liberomauris.edu"),(58,"Leigh","Ruiz","Aliquam.erat@convallis.co.uk"),(59,"Quail","Glover","consectetuer@interdum.org"),(60,"Hedda","Thompson","metus@elitdictum.ca");
INSERT INTO users (id,firstname,lastname,email) VALUES (61,"Xerxes","Watts","justo.eu.arcu@sodaleselit.co.uk"),(62,"Chandler","Dillon","amet.consectetuer.adipiscing@facilisisegetipsum.net"),(63,"Karina","Leon","interdum@placerat.edu"),(64,"Elijah","Williams","id.enim@magnaUttincidunt.com"),(65,"Cedric","Justice","dui.Fusce.diam@Nulla.com"),(66,"Blair","Nash","dictum.magna.Ut@natoquepenatibuset.ca"),(67,"Jeremy","Collins","nisl@auctornuncnulla.edu"),(68,"Jakeem","Wilkerson","Duis@purusgravida.org"),(69,"Sylvester","Rasmussen","odio.semper.cursus@tempusloremfringilla.org"),(70,"Adena","Finley","nisi.Cum.sociis@lectusjustoeu.org");
INSERT INTO users (id,firstname,lastname,email) VALUES (71,"Ariel","Boyd","est.tempor.bibendum@velitCras.co.uk"),(72,"Ria","Wong","interdum@pharetrafelis.co.uk"),(73,"Stephen","Slater","lobortis.Class.aptent@loremsitamet.co.uk"),(74,"Marny","Cardenas","pellentesque.eget@massa.co.uk"),(75,"Nissim","Wynn","ligula.Aenean@Vivamusmolestie.org"),(76,"Laurel","Parsons","pharetra.nibh@nisl.net"),(77,"Ursula","Hood","magna@Morbimetus.edu"),(78,"Robert","Garcia","dolor.nonummy@ametluctus.org"),(79,"Madaline","Downs","facilisis.Suspendisse@ac.net"),(80,"Deanna","Summers","vitae.risus@justoeuarcu.co.uk");
INSERT INTO users (id,firstname,lastname,email) VALUES (81,"Allistair","Santos","ullamcorper.velit@eratSed.net"),(82,"Graham","Juarez","malesuada@Proinvelarcu.org"),(83,"Gisela","Cooke","id@Sedidrisus.com"),(84,"Tasha","Hull","eu.tellus.eu@gravidanunc.com"),(85,"Reece","Duffy","Morbi.accumsan@aliquam.net"),(86,"Anthony","Dawson","ornare@purusDuis.ca"),(87,"Dora","Cannon","eros.non@nullaIntegervulputate.org"),(88,"Yasir","Landry","diam.Duis@esttempor.ca"),(89,"Candace","Mccray","Aliquam@amalesuada.edu"),(90,"Alden","Stein","primis@lacusCrasinterdum.net");
INSERT INTO users (id,firstname,lastname,email) VALUES (91,"Vivien","Hodges","diam.dictum.sapien@nonleo.ca"),(92,"Hammett","Chaney","molestie@quisdiamluctus.net"),(93,"Arthur","Dudley","malesuada.malesuada@nec.co.uk"),(94,"Hillary","Reid","tellus.id.nunc@rhoncus.ca"),(95,"Piper","Pruitt","diam.eu@metusvitae.edu"),(96,"Honorato","Anthony","aliquet@Duis.org"),(97,"Lavinia","Cotton","Etiam.ligula.tortor@duinectempus.co.uk"),(98,"Stuart","Sawyer","ipsum.Phasellus@euismodac.co.uk"),(99,"Victor","Mckay","sagittis.felis@semegestasblandit.co.uk"),(100,"Uta","Koch","placerat@porttitor.ca");
